version: '3.4'

services:
  sql:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=1Secure*Password1
      - MSSQL_TCP_PORT=1433
    ports: 
      - "1433:1433"
    volumes:
    - ./data:/var/opt/mssql/data
   
  data-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DataApiConnectionString=Server=host.docker.internal;Database=Hangfire;User Id=SA;Password=1Secure*Password1;MultipleActiveResultSets=true
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - sql
      
